### ISSUE TITLE
command line option for specifying the tertestrial.yml file

### ISSUE THREAD

**Issue by mjhm** [Originate/tertestrial-server#61]
Suggestion: allow a `--config <config .yml file>` option to the `tertestrial` command.

I'm not crazy about including the `tertestrial.yml` file in my project repo because it is (arguably) specific to a personal workflow and code editing process (even though it's editor agnostic).  Furthermore the `tertestrial.yml` file has nothing to do with the code operation, installation, or automated testing.  So it is (arguably) coding clutter. Allowing the user to point to a specific `.yml` config file would make `tertestrial` less opinionated about where and how the `tertestrial.yml` file should be saved.

**Comment by charlierudolph** [comment]
I agree it is a personal workflow that may even change between developers if one wants to run the command with different flags. Hmm, maybe we should just move to adding it to `.gitignore`.

Along that line to reduce duplication when we use the same tools, we could have the following policy:

When a `tertestrial.yml` file isn't found in the current directory we can try and load from the users home directory. Maybe `~/tertestrial_global.yml` which gives a mapping from project path to a tertestrial config.

For easier updating we could then add a `tertestrial import` which loads the config from the global config and writes it to the current directory. After updates, you could use `testestrial export` to save back the current directory config to the global config. Thus if you have multiple machines you just need to copy that single file.

The setup command could also allow you to choose other repos you have configured as starting points.

An example global config could be something like: 
```yml
default: &DEFAULT
  actions:
    test:
      - match:
          filename: '\.feature$'
        command: 'cucumber-js {{filename}}'
      - match:
          filename: '\.feature$'
          line: '\d+'
        command: 'cucumber-js {{filename}}:{{line}}'
      - match:
          filename: '\_spec.coffee$'
        command: 'mycha --reporter spec {{filename}}'
    lint:
      - match:
          filename: '\.coffee$'
        command: 'coffeelint {{filename}}'

path/to/originate-project-1: *DEFAULT
path/to/originate-project-2: *DEFAULT
path/to/cucumber-js:
  actions:
    test:
      - match:
          filename: '\.feature$'
        command: './bin/cucumber.js {{filename}}'
      - match:
          filename: '\.feature$'
          line: '\d+'
        command: './bin/cucumber.js {{filename}}:{{line}}'
      - match:
          filename: '\_spec.js$'
        command: 'mycha --reporter spec {{filename}}'

    lint:
      - match:
          filename: '\.js$'
        command: 'eslint {{filename}}'
```
Ideally the user doesn't really need to touch the global config but just updates it via tertestrial commands.
